server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
          initial-size: 5  # 初始化大小
          min-idle: 5  # 最小
          max-active: 100  # 最大
          max-wait: 60000  # 连接超时时间
          time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
          validationQuery: select 'x'
          test-while-idle: true  # 当连接空闲时，是否执行连接测试
          test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
          test-on-return: false  # 在连接归还到连接池时是否测试该连接
          filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          maxOpenPreparedStatements: 20
          web-stat-filter:
              enabled: true
              url-pattern: /*
              exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
              session-stat-enable: true
              session-stat-max-count: 10
          stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
              reset-enable: true
              login-username: admin
              login-password: admin

files:
  path: e:/files
#mybatis:
#  configuration:
#      mapUnderscoreToCamelCase: true
token:
  expire:
    seconds: 7200
  jwtSecret: (GUO:)_$^11244^%$_(HU:)_@@++--(JI:)_++++_.sds_(AAA:)
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml